using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace FoodDeliveryService.Modules.Users.Infrastructure.Database.Migrations;

/// <summary>
/// Seeds the Feature 3.6 support permission set and maps it to roles: the operational ticketing
/// codes to <c>SupportAgent</c>, all of them plus <c>refunds:approve</c> to <c>Administrator</c>,
/// and the two customer-facing codes to <c>Customer</c>. The codes are namespaced
/// <c>support-tickets:*</c> because the pre-existing <c>tickets:*</c> codes are event-ticketing
/// leftovers already granted to every customer.
/// </summary>
public partial class Add_Support_Role_Permissions : Migration
{
    /// <inheritdoc />
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "Generated by EF Core migrations.")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Generated by EF Core migrations.")]
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.InsertData(
            table: "permissions",
            column: "code",
            values: new object[]
            {
                "refunds:approve",
                "refunds:request",
                "support-analytics:read",
                "support-tickets:assign",
                "support-tickets:manage",
                "support-tickets:open",
                "support-tickets:read"
            });

        migrationBuilder.InsertData(
            table: "role_permissions",
            columns: new[] { "permission_code", "role_name" },
            values: new object[,]
            {
                { "refunds:approve", "Administrator" },
                { "refunds:request", "Administrator" },
                { "refunds:request", "SupportAgent" },
                { "support-analytics:read", "Administrator" },
                { "support-analytics:read", "SupportAgent" },
                { "support-tickets:assign", "Administrator" },
                { "support-tickets:assign", "SupportAgent" },
                { "support-tickets:manage", "Administrator" },
                { "support-tickets:manage", "SupportAgent" },
                { "support-tickets:open", "Administrator" },
                { "support-tickets:open", "Customer" },
                { "support-tickets:read", "Administrator" },
                { "support-tickets:read", "Customer" },
                { "support-tickets:read", "SupportAgent" }
            });
    }

    /// <inheritdoc />
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "Generated by EF Core migrations.")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Generated by EF Core migrations.")]
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "refunds:approve", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "refunds:request", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "refunds:request", "SupportAgent" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-analytics:read", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-analytics:read", "SupportAgent" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:assign", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:assign", "SupportAgent" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:manage", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:manage", "SupportAgent" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:open", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:open", "Customer" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:read", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:read", "Customer" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:read", "SupportAgent" });

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "refunds:approve");

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "refunds:request");

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "support-analytics:read");

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "support-tickets:assign");

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "support-tickets:manage");

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "support-tickets:open");

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "support-tickets:read");
    }
}
