using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FoodDeliveryService.Modules.Users.Infrastructure.Database.Migrations;

/// <summary>
/// Adds <c>support-tickets:administer</c> and grants it to <c>Administrator</c> only.
/// <para>
/// The support ownership bypass, mirroring <c>deliveries:administer</c>: agents and administrators
/// both hold <c>support-tickets:assign</c>, so both can claim a ticket and hand one back, and this
/// is the code that separates them — it gates assigning a ticket to somebody other than yourself.
/// A dedicated code rather than treating <c>refunds:approve</c> as an administrator marker, since
/// that would silently hand out ticket routing the day a senior agent is granted refund approval.
/// </para>
/// </summary>
public partial class Add_Support_Ticket_Administer_Permission : Migration
{
    /// <inheritdoc />
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "Generated by EF Core migrations.")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Generated by EF Core migrations.")]
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.InsertData(
            table: "permissions",
            column: "code",
            value: "support-tickets:administer");

        migrationBuilder.InsertData(
            table: "role_permissions",
            columns: new[] { "permission_code", "role_name" },
            values: new object[] { "support-tickets:administer", "Administrator" });
    }

    /// <inheritdoc />
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "Generated by EF Core migrations.")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Generated by EF Core migrations.")]
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "support-tickets:administer", "Administrator" });

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "support-tickets:administer");
    }
}
