using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace FoodDeliveryService.Modules.Users.Infrastructure.Database.Migrations;

/// <summary>
/// Seeds the Feature 3.8 payment permission set and maps it to roles: <c>payment-methods:manage</c>
/// and <c>payments:read</c> to <c>Customer</c>, all three to <c>Administrator</c>.
/// <para>
/// <c>payments:administer</c> is the ownership bypass, mirroring <c>deliveries:administer</c> and
/// <c>support-tickets:administer</c>: it is what lets an administrator read any payment rather than
/// only their own. Nothing is granted to <c>RestaurantManager</c>, <c>DeliveryDriver</c> or
/// <c>SupportAgent</c> — an agent who needs to see a payment gets it through the ticket context,
/// and <c>refunds:approve</c> is deliberately not widened to also mean "can see payments".
/// </para>
/// </summary>
public partial class Add_Payment_Permissions : Migration
{
    /// <inheritdoc />
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "Generated by EF Core migrations.")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Generated by EF Core migrations.")]
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.InsertData(
            table: "permissions",
            column: "code",
            values: new object[]
            {
                "payment-methods:manage",
                "payments:administer",
                "payments:read"
            });

        migrationBuilder.InsertData(
            table: "role_permissions",
            columns: new[] { "permission_code", "role_name" },
            values: new object[,]
            {
                { "payment-methods:manage", "Administrator" },
                { "payment-methods:manage", "Customer" },
                { "payments:administer", "Administrator" },
                { "payments:read", "Administrator" },
                { "payments:read", "Customer" }
            });
    }

    /// <inheritdoc />
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "Generated by EF Core migrations.")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Generated by EF Core migrations.")]
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "payment-methods:manage", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "payment-methods:manage", "Customer" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "payments:administer", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "payments:read", "Administrator" });

        migrationBuilder.DeleteData(
            table: "role_permissions",
            keyColumns: new[] { "permission_code", "role_name" },
            keyValues: new object[] { "payments:read", "Customer" });

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "payment-methods:manage");

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "payments:administer");

        migrationBuilder.DeleteData(
            table: "permissions",
            keyColumn: "code",
            keyValue: "payments:read");
    }
}
