// <auto-generated />
using System;
using FoodDeliveryService.Modules.Support.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodDeliveryService.Modules.Support.Infrastructure.Database.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    [Migration("20260831103529_Add_Refund_Requests")]
    partial class Add_Refund_Requests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("support_ticket_reference_seq");

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_inbox_messages_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_inbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_messages_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Support.Domain.Agents.SupportAgentReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_support_agents");

                    b.ToTable("support_agents", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Support.Domain.Audit.SupportAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("FromValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_value");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("ToValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_value");

                    b.HasKey("Id")
                        .HasName("pk_support_audit_entries");

                    b.HasIndex("TicketId", "OccurredOnUtc")
                        .HasDatabaseName("ix_support_audit_entries_ticket_id_occurred_on_utc");

                    b.ToTable("support_audit_entries", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Support.Domain.Orders.OrderSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("LastEventOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_on_utc");

                    b.Property<DateTime>("PlacedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_on_utc");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_order_snapshots");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_order_snapshots_customer_id");

                    b.ToTable("order_snapshots", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Support.Domain.Refunds.RefundRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("DecidedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_admin_id");

                    b.Property<DateTime?>("DecidedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_on_utc");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RequestedByAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_agent_id");

                    b.Property<DateTime>("RequestedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_on_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("TicketReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticket_reference");

                    b.HasKey("Id")
                        .HasName("pk_refund_requests");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_refund_requests_order_id")
                        .HasFilter("status IN (0, 1)");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_refund_requests_status");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_refund_requests_ticket_id");

                    b.ToTable("refund_requests", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Support.Domain.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_agent_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime?>("ClosedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_on_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("EscalationTranscript")
                        .HasColumnType("jsonb")
                        .HasColumnName("escalation_transcript");

                    b.Property<DateTime?>("FirstRespondedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_responded_on_utc");

                    b.Property<DateTime>("OpenedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_on_utc");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("ResolvedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_on_utc");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssignedAgentId")
                        .HasDatabaseName("ix_tickets_assigned_agent_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_tickets_customer_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_reference");

                    b.HasIndex("Status", "OpenedOnUtc")
                        .HasDatabaseName("ix_tickets_status_opened_on_utc");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Support.Domain.Tickets.TicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<int>("AuthorKind")
                        .HasColumnType("integer")
                        .HasColumnName("author_kind");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("PostedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_on_utc");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_ticket_messages");

                    b.HasIndex("TicketId", "PostedOnUtc")
                        .HasDatabaseName("ix_ticket_messages_ticket_id_posted_on_utc");

                    b.ToTable("ticket_messages", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Support.Domain.Refunds.RefundRequest", b =>
                {
                    b.HasOne("FoodDeliveryService.Modules.Support.Domain.Tickets.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refund_requests_tickets_ticket_id");
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Support.Domain.Tickets.TicketMessage", b =>
                {
                    b.HasOne("FoodDeliveryService.Modules.Support.Domain.Tickets.Ticket", null)
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_messages_tickets_ticket_id");
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Support.Domain.Tickets.Ticket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
