version: '3.9'

services:
  fooddeliveryservice.api:
    image: ${DOCKER_REGISTRY-}fooddeliveryserviceapi
    container_name: FoodDeliveryService.Api
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  fooddeliveryservice.notifications.api:
    image: ${DOCKER_REGISTRY-}fooddeliveryservicenotificationsapi
    container_name: FoodDeliveryService.Notifications.Api
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Notifications.Api/Dockerfile
    ports:
      - 5100:8080
      - 5101:8081

  fooddeliveryservice.gateway:
    image: ${DOCKER_REGISTRY-}fooddeliveryservicegateway
    container_name: FoodDeliveryService.Gateway
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Gateway/Dockerfile
    ports:
      - 3000:8080
      - 3001:8081

  fooddeliveryservice.database:
    image: postgres:17
    container_name: FoodDeliveryService.Database
    environment:
      - POSTGRES_DB=fooddeliveryservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  fooddeliveryservice.identity:
    image: quay.io/keycloak/keycloak:26.5.1
    container_name: FoodDeliveryService.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
      - 9000:9000
    user: root # Required to set volume permissions

  fooddeliveryservice.seq:
    image: datalust/seq:2025.2
    container_name: FoodDeliveryService.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true # local dev only
    ports:
      - 5341:5341
      - 8081:80

  fooddeliveryservice.redis:
    image: redis:latest
    container_name: FoodDeliveryService.Redis
    restart: always
    ports:
      - 6379:6379

  fooddeliveryservice.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: FoodDeliveryService.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686

  fooddeliveryservice.queue:
    image: rabbitmq:management-alpine
    container_name: FoodDeliveryService.Queue
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672