version: '3.9'

services:
  fooddeliveryservice.notifications.api:
    image: ${DOCKER_REGISTRY-}fooddeliveryservicenotificationsapi
    container_name: FoodDeliveryService.Notifications.Api
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Notifications.Api/Dockerfile
    ports:
      - 5100:8080
      - 5101:8081

  fooddeliveryservice.orders.api:
    image: ${DOCKER_REGISTRY-}fooddeliveryserviceordersapi
    container_name: FoodDeliveryService.Orders.Api
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Orders.Api/Dockerfile
    ports:
      - 5200:8080
      - 5201:8081

  fooddeliveryservice.restaurants.api:
    image: ${DOCKER_REGISTRY-}fooddeliveryservicerestaurantsapi
    container_name: FoodDeliveryService.Restaurants.Api
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Restaurants.Api/Dockerfile
    ports:
      - 5300:8080
      - 5301:8081

  fooddeliveryservice.users.api:
    image: ${DOCKER_REGISTRY-}fooddeliveryserviceusersapi
    container_name: FoodDeliveryService.Users.Api
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Users.Api/Dockerfile
    ports:
      - 5400:8080
      - 5401:8081

  fooddeliveryservice.delivery.api:
    image: ${DOCKER_REGISTRY-}fooddeliveryservicedeliveryapi
    container_name: FoodDeliveryService.Delivery.Api
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Delivery.Api/Dockerfile
    ports:
      - 5500:8080
      - 5501:8081

  fooddeliveryservice.realtime.api:
    image: ${DOCKER_REGISTRY-}fooddeliveryservicerealtimeapi
    container_name: FoodDeliveryService.RealTime.Api
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.RealTime.Api/Dockerfile
    ports:
      - 5600:8080
      - 5601:8081

  fooddeliveryservice.gateway:
    image: ${DOCKER_REGISTRY-}fooddeliveryservicegateway
    container_name: FoodDeliveryService.Gateway
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Gateway/Dockerfile
    ports:
      - 3000:8080
      - 3001:8081

  fooddeliveryservice.database:
    image: postgres:17
    container_name: FoodDeliveryService.Database
    environment:
      - POSTGRES_DB=fooddeliveryservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  fooddeliveryservice.identity:
    image: ${DOCKER_REGISTRY-}fooddeliveryserviceidentity
    container_name: FoodDeliveryService.Identity
    build:
      context: .
      dockerfile: src/API/FoodDeliveryService.Identity/Dockerfile
    depends_on:
      - fooddeliveryservice.database
    ports:
      - 18080:8080
      - 18081:8081

  fooddeliveryservice.seq:
    image: datalust/seq:2025.2
    container_name: FoodDeliveryService.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true # local dev only
    ports:
      - 5341:5341
      - 8081:80

  fooddeliveryservice.redis:
    image: redis:latest
    container_name: FoodDeliveryService.Redis
    restart: always
    ports:
      - 6379:6379

  fooddeliveryservice.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: FoodDeliveryService.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686

  fooddeliveryservice.queue:
    image: rabbitmq:management-alpine
    container_name: FoodDeliveryService.Queue
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
  