<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\FoodDeliveryService.Common.Application\FoodDeliveryService.Common.Application.csproj" />
    <ProjectReference Include="..\FoodDeliveryService.Modules.Payments.Domain\FoodDeliveryService.Modules.Payments.Domain.csproj" />
    <ProjectReference Include="..\FoodDeliveryService.Modules.Payments.IntegrationEvents\FoodDeliveryService.Modules.Payments.IntegrationEvents.csproj" />
  </ItemGroup>

</Project>
