using FoodDeliveryService.Common.Domain;

namespace FoodDeliveryService.Modules.Users.Domain.Users;

/// <summary>
/// Raised when an account is provisioned by invitation (no password). Carries the one-time
/// activation token + expiry generated by the identity provider so the Application layer can
/// publish a UserInvitedIntegrationEvent and Notifications can email the activation link. The token
/// is transient (never persisted on the User entity).
/// </summary>
public sealed class UserInvitedDomainEvent(
    Guid userId,
    string email,
    string firstName,
    string lastName,
    string activationToken,
    DateTime expiresOnUtc) : DomainEvent
{
    public Guid UserId { get; init; } = userId;

    public string Email { get; init; } = email;

    public string FirstName { get; init; } = firstName;

    public string LastName { get; init; } = lastName;

    public string ActivationToken { get; init; } = activationToken;

    public DateTime ExpiresOnUtc { get; init; } = expiresOnUtc;
}
