// <auto-generated />
using System;
using FoodDeliveryService.Modules.FraudDetection.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodDeliveryService.Modules.FraudDetection.Infrastructure.Database.Migrations
{
    [DbContext(typeof(FraudDetectionDbContext))]
    [Migration("20260807113835_Create_Database")]
    partial class Create_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_inbox_messages_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_messages_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.FraudDetection.Domain.Customers.CustomerBehaviour", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CancelledBeforePickup")
                        .HasColumnType("integer")
                        .HasColumnName("cancelled_before_pickup");

                    b.Property<DateTime>("FirstSeenOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_on_utc");

                    b.Property<DateTime?>("LastOrderOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_order_on_utc");

                    b.Property<int>("OrdersCancelled")
                        .HasColumnType("integer")
                        .HasColumnName("orders_cancelled");

                    b.Property<int>("OrdersCancelledInWindow")
                        .HasColumnType("integer")
                        .HasColumnName("orders_cancelled_in_window");

                    b.Property<int>("OrdersDelivered")
                        .HasColumnType("integer")
                        .HasColumnName("orders_delivered");

                    b.Property<int>("OrdersPlaced")
                        .HasColumnType("integer")
                        .HasColumnName("orders_placed");

                    b.Property<int>("OrdersPlacedInWindow")
                        .HasColumnType("integer")
                        .HasColumnName("orders_placed_in_window");

                    b.Property<int>("OrdersRejected")
                        .HasColumnType("integer")
                        .HasColumnName("orders_rejected");

                    b.Property<DateTime?>("RegisteredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_on_utc");

                    b.Property<decimal>("TotalOrderValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_order_value");

                    b.Property<DateTime>("WindowStartedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_started_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_customer_behaviours");

                    b.HasIndex("LastOrderOnUtc")
                        .HasDatabaseName("ix_customer_behaviours_last_order_on_utc");

                    b.ToTable("customer_behaviours", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.FraudDetection.Domain.Drivers.DriverBehaviour", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DeliveriesCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("deliveries_completed");

                    b.Property<DateTime>("FirstSeenOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_on_utc");

                    b.Property<DateTime?>("LastDeliveryOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_delivery_on_utc");

                    b.Property<int>("LocationMismatches")
                        .HasColumnType("integer")
                        .HasColumnName("location_mismatches");

                    b.Property<int>("OffersRejected")
                        .HasColumnType("integer")
                        .HasColumnName("offers_rejected");

                    b.Property<int>("PickupsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("pickups_completed");

                    b.HasKey("Id")
                        .HasName("pk_driver_behaviours");

                    b.HasIndex("LastDeliveryOnUtc")
                        .HasDatabaseName("ix_driver_behaviours_last_delivery_on_utc");

                    b.ToTable("driver_behaviours", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.FraudDetection.Domain.Orders.OrderFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_on_utc");

                    b.Property<bool>("CancelledBeforePickup")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelled_before_pickup");

                    b.Property<DateTime?>("CancelledOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_on_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeliveredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_on_utc");

                    b.Property<Guid?>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<double?>("DropoffLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("dropoff_latitude");

                    b.Property<double?>("DropoffLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("dropoff_longitude");

                    b.Property<DateTime?>("LastUnassignedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_unassigned_on_utc");

                    b.Property<DateTime?>("PickedUpOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_on_utc");

                    b.Property<DateTime>("PlacedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_on_utc");

                    b.Property<DateTime?>("ReadyForPickupOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_for_pickup_on_utc");

                    b.Property<DateTime?>("RejectedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_on_utc");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("TimesUnassigned")
                        .HasColumnType("integer")
                        .HasColumnName("times_unassigned");

                    b.HasKey("Id")
                        .HasName("pk_order_facts");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_order_facts_delivery_id");

                    b.HasIndex("PlacedOnUtc")
                        .HasDatabaseName("ix_order_facts_placed_on_utc");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_order_facts_restaurant_id");

                    b.HasIndex("CustomerId", "PlacedOnUtc")
                        .HasDatabaseName("ix_order_facts_customer_id_placed_on_utc");

                    b.ToTable("order_facts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
