<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\FoodDeliveryService.Common.Application\FoodDeliveryService.Common.Application.csproj" />
    <ProjectReference Include="..\FoodDeliveryService.Modules.Restaurants.Domain\FoodDeliveryService.Modules.Restaurants.Domain.csproj" />
    <ProjectReference Include="..\FoodDeliveryService.Modules.Restaurants.IntegrationEvents\FoodDeliveryService.Modules.Restaurants.IntegrationEvents.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FoodDeliveryService.Modules.Restaurants.UnitTests" />
  </ItemGroup>

</Project>
