// <auto-generated />
using System;
using System.Collections.Generic;
using FoodDeliveryService.Modules.Delivery.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodDeliveryService.Modules.Delivery.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    [Migration("20260804140748_Add_Message_Correlation_Columns")]
    partial class Add_Message_Correlation_Columns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_inbox_messages_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_messages_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Delivery.Domain.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AssignedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_on_utc");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeliveredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_on_utc");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("OfferExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_expires_on_utc");

                    b.Property<Guid?>("OfferedDriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("offered_driver_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PickedUpOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_on_utc");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<Guid>>("_triedDriverIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("tried_driver_ids");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_deliveries_driver_id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_deliveries_order_id");

                    b.HasIndex("Status", "OfferExpiresOnUtc")
                        .HasDatabaseName("ix_deliveries_status_offer_expires_on_utc");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Delivery.Domain.Drivers.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("OnboardedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarded_on_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("pk_drivers");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Delivery.Domain.Drivers.DriverLocationHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_driver_location_history");

                    b.HasIndex("DriverId", "RecordedOnUtc")
                        .HasDatabaseName("ix_driver_location_history_driver_id_recorded_on_utc");

                    b.ToTable("driver_location_history", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Delivery.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("PlacedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_on_utc");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_orders_restaurant_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Delivery.Domain.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Delivery.Domain.Deliveries.Delivery", b =>
                {
                    b.OwnsOne("FoodDeliveryService.Modules.Delivery.Domain.Shared.DeliveryAddress", "DropoffAddress", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("dropoff_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("dropoff_country");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("dropoff_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("dropoff_longitude");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("dropoff_notes");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("dropoff_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("dropoff_street");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.OwnsOne("FoodDeliveryService.Modules.Delivery.Domain.Shared.GeoCoordinate", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_longitude");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.Navigation("DropoffAddress")
                        .IsRequired();

                    b.Navigation("PickupLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("FoodDeliveryService.Modules.Delivery.Domain.Orders.Order", b =>
                {
                    b.OwnsOne("FoodDeliveryService.Modules.Delivery.Domain.Shared.DeliveryAddress", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("delivery_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("delivery_country");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_longitude");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("delivery_notes");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("delivery_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("delivery_street");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_id");
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
