// <auto-generated />
using System;
using FoodDeliveryService.Modules.Payments.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodDeliveryService.Modules.Payments.Infrastructure.Database.Migrations;

[DbContext(typeof(PaymentsDbContext))]
[Migration("20260915070613_Add_Payments")]
partial class Add_Payments
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Inbox.InboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("jsonb")
                    .HasColumnName("content");

                b.Property<string>("CorrelationId")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("correlation_id");

                b.Property<string>("Error")
                    .HasColumnType("text")
                    .HasColumnName("error");

                b.Property<DateTime>("OccurredOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occurred_on_utc");

                b.Property<DateTime?>("ProcessedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("processed_on_utc");

                b.Property<string>("TraceParent")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("trace_parent");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_inbox_messages");

                b.HasIndex("CorrelationId")
                    .HasDatabaseName("ix_inbox_messages_correlation_id")
                    .HasFilter("correlation_id IS NOT NULL");

                b.HasIndex("OccurredOnUtc")
                    .HasDatabaseName("ix_inbox_messages_unprocessed")
                    .HasFilter("processed_on_utc IS NULL");

                b.ToTable("inbox_messages", (string)null);
            });

        modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
            {
                b.Property<Guid>("InboxMessageId")
                    .HasColumnType("uuid")
                    .HasColumnName("inbox_message_id");

                b.Property<string>("Name")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("name");

                b.HasKey("InboxMessageId", "Name")
                    .HasName("pk_inbox_message_consumers");

                b.ToTable("inbox_message_consumers", (string)null);
            });

        modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Outbox.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("jsonb")
                    .HasColumnName("content");

                b.Property<string>("CorrelationId")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("correlation_id");

                b.Property<string>("Error")
                    .HasColumnType("text")
                    .HasColumnName("error");

                b.Property<DateTime>("OccurredOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occurred_on_utc");

                b.Property<DateTime?>("ProcessedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("processed_on_utc");

                b.Property<string>("TraceParent")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("trace_parent");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_outbox_messages");

                b.HasIndex("CorrelationId")
                    .HasDatabaseName("ix_outbox_messages_correlation_id")
                    .HasFilter("correlation_id IS NOT NULL");

                b.HasIndex("OccurredOnUtc")
                    .HasDatabaseName("ix_outbox_messages_unprocessed")
                    .HasFilter("processed_on_utc IS NULL");

                b.ToTable("outbox_messages", (string)null);
            });

        modelBuilder.Entity("FoodDeliveryService.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
            {
                b.Property<Guid>("OutboxMessageId")
                    .HasColumnType("uuid")
                    .HasColumnName("outbox_message_id");

                b.Property<string>("Name")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("name");

                b.HasKey("OutboxMessageId", "Name")
                    .HasName("pk_outbox_message_consumers");

                b.ToTable("outbox_message_consumers", (string)null);
            });

        modelBuilder.Entity("FoodDeliveryService.Modules.Payments.Domain.PaymentMethods.CustomerPaymentProfile", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime?>("AttachedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("attached_on_utc");

                b.Property<string>("Brand")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("brand");

                b.Property<DateTime>("CreatedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_on_utc");

                b.Property<int?>("ExpiryMonth")
                    .HasColumnType("integer")
                    .HasColumnName("expiry_month");

                b.Property<int?>("ExpiryYear")
                    .HasColumnType("integer")
                    .HasColumnName("expiry_year");

                b.Property<string>("Last4")
                    .HasMaxLength(4)
                    .HasColumnType("character varying(4)")
                    .HasColumnName("last4");

                b.Property<Guid?>("PaymentMethodId")
                    .HasColumnType("uuid")
                    .HasColumnName("payment_method_id");

                b.Property<string>("StripeCustomerId")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("stripe_customer_id");

                b.Property<string>("StripePaymentMethodId")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("stripe_payment_method_id");

                b.HasKey("Id")
                    .HasName("pk_customer_payment_profiles");

                b.HasIndex("PaymentMethodId")
                    .IsUnique()
                    .HasDatabaseName("ix_customer_payment_profiles_payment_method_id")
                    .HasFilter("payment_method_id IS NOT NULL");

                b.HasIndex("StripeCustomerId")
                    .IsUnique()
                    .HasDatabaseName("ix_customer_payment_profiles_stripe_customer_id");

                b.ToTable("customer_payment_profiles", (string)null);
            });

        modelBuilder.Entity("FoodDeliveryService.Modules.Payments.Domain.Payments.Payment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime?>("AuthorizedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("authorized_on_utc");

                b.Property<DateTime>("CreatedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_on_utc");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uuid")
                    .HasColumnName("customer_id");

                b.Property<DateTime?>("FailedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("failed_on_utc");

                b.Property<string>("FailureReason")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("failure_reason");

                b.Property<Guid>("OrderId")
                    .HasColumnType("uuid")
                    .HasColumnName("order_id");

                b.Property<int>("Status")
                    .HasColumnType("integer")
                    .HasColumnName("status");

                b.Property<string>("StripePaymentIntentId")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("stripe_payment_intent_id");

                b.HasKey("Id")
                    .HasName("pk_payments");

                b.HasIndex("CustomerId")
                    .HasDatabaseName("ix_payments_customer_id");

                b.HasIndex("OrderId")
                    .IsUnique()
                    .HasDatabaseName("ix_payments_order_id");

                b.HasIndex("StripePaymentIntentId")
                    .IsUnique()
                    .HasDatabaseName("ix_payments_stripe_payment_intent_id")
                    .HasFilter("stripe_payment_intent_id IS NOT NULL");

                b.ToTable("payments", (string)null);
            });

        modelBuilder.Entity("FoodDeliveryService.Modules.Payments.Domain.Webhooks.StripeEventLog", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("CustomerReference")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("customer_reference");

                b.Property<string>("Error")
                    .HasColumnType("text")
                    .HasColumnName("error");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("event_type");

                b.Property<string>("FailureReason")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("failure_reason");

                b.Property<string>("ObjectId")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("object_id");

                b.Property<string>("ObjectStatus")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("object_status");

                b.Property<string>("OrderReference")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("order_reference");

                b.Property<string>("PaymentMethodReference")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("payment_method_reference");

                b.Property<DateTime?>("ProcessedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("processed_on_utc");

                b.Property<string>("ProviderEventId")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("provider_event_id");

                b.Property<DateTime>("ReceivedOnUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("received_on_utc");

                b.HasKey("Id")
                    .HasName("pk_stripe_event_logs");

                b.HasIndex("ProviderEventId")
                    .IsUnique()
                    .HasDatabaseName("ix_stripe_event_logs_provider_event_id");

                b.HasIndex("ReceivedOnUtc")
                    .HasDatabaseName("ix_stripe_event_logs_received_on_utc")
                    .HasFilter("processed_on_utc IS NULL");

                b.ToTable("stripe_event_logs", (string)null);
            });

        modelBuilder.Entity("FoodDeliveryService.Modules.Payments.Domain.Payments.Payment", b =>
            {
                b.OwnsOne("FoodDeliveryService.Modules.Payments.Domain.Money", "Amount", b1 =>
                    {
                        b1.Property<Guid>("PaymentId")
                            .HasColumnType("uuid")
                            .HasColumnName("id");

                        b1.Property<decimal>("Amount")
                            .HasPrecision(10, 2)
                            .HasColumnType("numeric(10,2)")
                            .HasColumnName("amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasMaxLength(3)
                            .HasColumnType("character varying(3)")
                            .HasColumnName("currency");

                        b1.HasKey("PaymentId");

                        b1.ToTable("payments");

                        b1.WithOwner()
                            .HasForeignKey("PaymentId")
                            .HasConstraintName("fk_payments_payments_id");
                    });

                b.Navigation("Amount")
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
