<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\FoodDeliveryService.Common.Presentation\FoodDeliveryService.Common.Presentation.csproj" />
    <ProjectReference Include="..\FoodDeliveryService.Modules.Support.Application\FoodDeliveryService.Modules.Support.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FoodDeliveryService.Modules.Support.IntegrationTests" />
  </ItemGroup>

</Project>
