FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["API/Evently.Api/Evently.Api.csproj", "API/Evently.Api/"]
COPY ["Common/FoodDeliveryService.Common.Application/FoodDeliveryService.Common.Application.csproj", "Common/FoodDeliveryService.Common.Application/"]
COPY ["Common/FoodDeliveryService.Common.Domain/FoodDeliveryService.Common.Domain.csproj", "Common/FoodDeliveryService.Common.Domain/"]
COPY ["Common/FoodDeliveryService.Common.Infrastructure/FoodDeliveryService.Common.Infrastructure.csproj", "Common/FoodDeliveryService.Common.Infrastructure/"]
COPY ["Common/FoodDeliveryService.Common.Presentation/FoodDeliveryService.Common.Presentation.csproj", "Common/FoodDeliveryService.Common.Presentation/"]
COPY ["Modules/Attendance/FoodDeliveryService.Modules.Attendance.Application/FoodDeliveryService.Modules.Attendance.Application.csproj", "Modules/Attendance/FoodDeliveryService.Modules.Attendance.Application/"]
COPY ["Modules/Attendance/FoodDeliveryService.Modules.Attendance.Domain/FoodDeliveryService.Modules.Attendance.Domain.csproj", "Modules/Attendance/FoodDeliveryService.Modules.Attendance.Domain/"]
COPY ["Modules/Attendance/FoodDeliveryService.Modules.Attendance.Infrastructure/FoodDeliveryService.Modules.Attendance.Infrastructure.csproj", "Modules/Attendance/FoodDeliveryService.Modules.Attendance.Infrastructure/"]
COPY ["Modules/Attendance/FoodDeliveryService.Modules.Attendance.IntegrationEvents/FoodDeliveryService.Modules.Attendance.IntegrationEvents.csproj", "Modules/Attendance/FoodDeliveryService.Modules.Attendance.IntegrationEvents/"]
COPY ["Modules/Attendance/FoodDeliveryService.Modules.Attendance.Presentation/FoodDeliveryService.Modules.Attendance.Presentation.csproj", "Modules/Attendance/FoodDeliveryService.Modules.Attendance.Presentation/"]
COPY ["Modules/Events/FoodDeliveryService.Modules.Events.Application/FoodDeliveryService.Modules.Events.Application.csproj", "Modules/Events/FoodDeliveryService.Modules.Events.Application/"]
COPY ["Modules/Events/FoodDeliveryService.Modules.Events.Domain/FoodDeliveryService.Modules.Events.Domain.csproj", "Modules/Events/FoodDeliveryService.Modules.Events.Domain/"]
COPY ["Modules/Events/FoodDeliveryService.Modules.Events.Infrastructure/FoodDeliveryService.Modules.Events.Infrastructure.csproj", "Modules/Events/FoodDeliveryService.Modules.Events.Infrastructure/"]
COPY ["Modules/Events/FoodDeliveryService.Modules.Events.IntegrationEvents/FoodDeliveryService.Modules.Events.IntegrationEvents.csproj", "Modules/Events/FoodDeliveryService.Modules.Events.IntegrationEvents/"]
COPY ["Modules/Events/FoodDeliveryService.Modules.Events.Presentation/FoodDeliveryService.Modules.Events.Presentation.csproj", "Modules/Events/FoodDeliveryService.Modules.Events.Presentation/"]
COPY ["Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.Application/FoodDeliveryService.Modules.Ticketing.Application.csproj", "Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.Application/"]
COPY ["Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.Domain/FoodDeliveryService.Modules.Ticketing.Domain.csproj", "Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.Domain/"]
COPY ["Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.Infrastructure/FoodDeliveryService.Modules.Ticketing.Infrastructure.csproj", "Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.Infrastructure/"]
COPY ["Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.IntegrationEvents/FoodDeliveryService.Modules.Ticketing.IntegrationEvents.csproj", "Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.IntegrationEvents/"]
COPY ["Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.Presentation/FoodDeliveryService.Modules.Ticketing.Presentation.csproj", "Modules/Ticketing/FoodDeliveryService.Modules.Ticketing.Presentation/"]
COPY ["Modules/Users/FoodDeliveryService.Modules.Users.Application/FoodDeliveryService.Modules.Users.Application.csproj", "Modules/Users/FoodDeliveryService.Modules.Users.Application/"]
COPY ["Modules/Users/FoodDeliveryService.Modules.Users.Domain/FoodDeliveryService.Modules.Users.Domain.csproj", "Modules/Users/FoodDeliveryService.Modules.Users.Domain/"]
COPY ["Modules/Users/FoodDeliveryService.Modules.Users.Infrastructure/FoodDeliveryService.Modules.Users.Infrastructure.csproj", "Modules/Users/FoodDeliveryService.Modules.Users.Infrastructure/"]
COPY ["Modules/Users/FoodDeliveryService.Modules.Users.IntegrationEvents/FoodDeliveryService.Modules.Users.IntegrationEvents.csproj", "Modules/Users/FoodDeliveryService.Modules.Users.IntegrationEvents/"]
COPY ["Modules/Users/FoodDeliveryService.Modules.Users.Presentation/FoodDeliveryService.Modules.Users.Presentation.csproj", "Modules/Users/FoodDeliveryService.Modules.Users.Presentation/"]
RUN dotnet restore "./API/Evently.Api/Evently.Api.csproj"
COPY . .
WORKDIR "/src/API/Evently.Api"
RUN dotnet build "./Evently.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Evently.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Evently.Api.dll"]