<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>420794d3-6b7d-4b6c-aa82-1c3823affe61</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Orders\FoodDeliveryService.Modules.Orders.Infrastructure\FoodDeliveryService.Modules.Orders.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Users\FoodDeliveryService.Modules.Users.Infrastructure\FoodDeliveryService.Modules.Users.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Restaurants\FoodDeliveryService.Modules.Restaurants.Infrastructure\FoodDeliveryService.Modules.Restaurants.Infrastructure.csproj" />
  </ItemGroup>

</Project>
