<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>420794d3-6b7d-4b6c-aa82-1c3823affe61</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="SonarAnalyzer.CSharp" Version="10.27.0.140913" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Users\FoodDeliveryService.Modules.Users.Infrastructure\FoodDeliveryService.Modules.Users.Infrastructure.csproj" />
  </ItemGroup>

</Project>
